name: Build Docker Container after Django Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_django:
    uses: 3hcw4smqonom7sw7pc5k/CS3300CCProject/.github/workflows/django-test.yaml@main
  container_builder:
    runs-on: ubuntu-latest
    needs: [test_django]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container image
        run: |
          docker build \
          -t your-username/your-image-name:${GITHUB_SHA::7} \
          -t your-username/your-image-name:latest \
          .
